agnilondapakou/helloWorld

README.md
This PR adds the following
1. Hello World in JavaScript
2. I have also added a list of available languages section in readme.md
I am starting my this hacktoberfest journey from your repository. Please accept the PR and also add the necessary labels before merging. Happy Hacktoberfest 2024! 🎉
=> Added helloWorld.js 

source/helloworld.cs
This pull request adds a simple **"Hello World"** program implemented in C#. The program outputs the message "Hello, World!" to the console.
- Created a new `helloworld.cs` file containing the C# code.
- The program uses `Console.WriteLine` to display the message.
This PR addresses **Issue [#15](https://github.com/agnilondapakou/helloWorld/issues/15)**.
Please review and let me know if any changes are needed.
=> "Hello World" Programm in C#

source/helloworld.asm
This pull request adds a simple **"Hello, World!"** program written in **x86 Assembly** for Linux. The program uses system calls to print "Hello, World!" to the console and then terminates.
- Added the file `helloworld.asm`, which contains the assembly code.
- The program uses the `sys_write` and `sys_exit` system calls to output the message and exit cleanly.
This PR resolves **Issue [#9](https://github.com/agnilondapakou/helloWorld/issues/9)**.
Please review and let me know if any changes or improvements are required.
=> "Hello World" Program in Assembly

source/helloworld.php
This pull request introduces a basic **"Hello, World!"** program written in **PHP**. The program simply outputs the message "Hello, World!" when executed.
- Added a new file `helloworld.php` containing the PHP code to display the message.
This PR addresses **Issue [#6](https://github.com/agnilondapakou/helloWorld/issues/6)**.
Please review and provide feedback if any adjustments are needed.
=> "Hello World" Program in PHP

source/helloworld.dart
This pull request introduces a simple **"Hello, World!"** program written in **Dart**. The program outputs the message "Hello, World!" to the console.
- Added a new file `helloworld.dart` containing the Dart code that implements the Hello World functionality.
This PR addresses **Issue [#7](https://github.com/agnilondapakou/helloWorld/issues/7)**.
Please review and let me know if there are any changes or improvements needed.
=> "Hello World" Program in Dart

source/helloworld.go
just go into source folder and execute 
`go run helloworld.go`
and bingooooooooooooooooooooo
=> Added Hello World in GO

README.md, source/helloworld.gd, source/helloworld.java
add helloworld for java and gdscript
=> feat: add langugage support Java and GDScript

source/helloworld.go, source/helloworld.java
=> Pull request for hello world, add java and golang

README.md, source/helloworld.rs, source/helloworld.ts
Written a Java program in Typescript and Rust.
Issue#33
=> Issue#33 Added a hello World program in Rust and Typesc

README.md, source/helloworld.zig
Added the Zig language and updated README.md accordingly please merge
=> Added language zig

README.md, source/helloworld.lua
=> Add language lua

README.md, source/helloworld.swift
I have added HelloWorld Program in Swift language and Updated README.md
=> Issue: #41 Added HelloWorld in Swift Language and Updated README.md

README.md, source/helloworld.R
This pull request adds a Hello World program written in R
=> Add Hello World in R

README.md, source/helloworld.pl
added helloworld.pl in source and updated README.md
=> Add Hello World in Prolog

README.md, source/hello.f90
HelloWorld in Fortran language added.
Version used is f90
=> Fortran added

source/helloworld.hs
Created hello world in haskell
=> Hello world in haskell

README.md, source/helloworld.fs
I have tried to add a hello world in F#. You can check the code [here](https://github.com/Just2sire/helloWorld/blob/add_helloworld_in_F%23/source/helloworld.fs).
This code is for the issue #75
=> Add helloworld in f#

README.md, source/helloworld.sno
=> Added Hello World in SNOBOL

helloworld.scala, source/helloworld.scm
Have Added Hello World Program in Scala Language kindly verify!
=> Added Hello World Program in Scala Language

README.md, source/helloworld.scm, source/helloworld.wl
"Hello, World!" program in Wolfram Language (also known as Mathematica)
=> "Hello, World!" program in Wolfram Language (also known as Mathematica)

source/hello.st
This code sends the displayNl message to the string 'Hello, World!', which will print it to the console.
=> Added "Hello world" in Smalltalk

README.md, source/helloworld.k
Added Hello World in K programming Language 
{request to kindly review the pull request for scheme language and accept it if possible}
=> Added Hello World in K programming Language 

README.md, helloworld.ijs
Added Hello World Program in J language
=> Added Hello World Program in J language

source/helloworld.apl
Adding Hello world in APL programming language as permitted in PR #120. kindly add hacktoberfest2024-accepted
=> Adding Hello world in APL programming language as permitted in PR #120

source/helloworld.erl
I've add hello world in Erlang to solve the issue #69 . So you can check my code [here](https://github.com/Just2sire/helloWorld/blob/add_helloworld_in_erlang/source/helloworld.erl). Check it out and tell me if the PR is valid
=> Adding hello world in Erlang

README.md, source/basic/helloworld.pas
Added Hello World in Pascal language
=> Added Hello World in Pascal language 

README.md, source/HelloWorld.cr
Added Hello World in Crystal programming languge
=> Added Hello World in Crystal programming languge

README.md, source/basic/helloworld.d
Added Hello World in  D programming language
=> Added Hello World in  D programming language

README.md, source/basic/helloworld.d, source/helloWorld.dylan
Added Hello World in Dylan programming language
=> Added Hello World in Dylan programming language

README.md, source/basic/helloworld.d, source/helloWorld.dylan, source/helloWorld.rkt
Added hello World in Racket programming language
=> Added hello World in Racket programming language

source/basic/hello.hx
Hello @agnilondapakou Hello world in Hexa language added in source folder. Please check my pull request and accept it. Thank you.
=> Hello world in Hexa language added.

README.md
Hello @agnilondapakou Erlang language added in README file.
=> Erlang language added in Readme file

README.md, source/basic/hello.jl
Added the hello world program for Julia programming language and updated the readme file appropriately. Thank you!
=> added julia-basic

README.md
Add Hexa programming language in the Readme file with official website
=> Add Hexa programming language in Readme file

source/basic/hello_world.exs
#83 Added the hello world in Elixir Language
=> Added the Hello World in Elixir Language

README.md
=> Add OCaml to README.md

README.md
Add Tcl Language point in the README.md file
=> Update README.md with Tcl in "List of available languages"

README.md
=> docs: add PureScript to available languages

README.md, source/basic/hello_world.clj
Added the hello_world.clj file and added clojure in README.md
=> Add clojure hello world.

README.md
i updated the README file by adding Objective-C programming language in it.
=> Add Objective-C programming language to the README file

README.md, source/basic/helloworld.plug
added plug programming language to the list of available language and also made changes in README.md according to it.
=> Added Plug programming language to the list of available languages

README.md
updated Groovy language as an available language in README.md file
=> Added Groovy as an available language

README.md
Added the falcon language to available languages in readme file
=> Added Falcon to Readme

source/basic/helloworld.vim
Add a comment and print hello world in Vim script!
=> feat: add Vim script helloworld

source/basic/HelloWorld.cj
add helloWorld in cangjie language
=> add helloWorld in cangjie language

README.md, source/basic/helloworld.pony
Here is the comment for your pull request, including the reference to the issue:
---
This pull request includes the addition of a new programming language example and its corresponding documentation update.
New language example added:
* [`source/basic/helloworld.pony`](diffhunk://#diff-349221cfd08afe47331dacc397cee8bd4595b86563929815f38291da8a1742dfR1-R3): Added a "Hello, World!" example in Pony.
Documentation update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R107): Added Pony to the list of programming languages in the "Hello, World!" examples section.
Fixes [Add Hello, World! in Pony Language. #224](https://github.com/agnilondapakou/helloWorld/issues/224)
---
=> Add Pony programming language to the list of supported languages.

README.md, source/basic/helloworld.au3
This pull request includes the addition of a new "Hello World" example in AutoIt to the repository. The most important changes include updating the `README.md` file to include AutoIt and adding the corresponding `helloworld.au3` file.
Additions to the repository:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R108-R109): Added a new entry for AutoIt in the list of "Hello World" examples.
* [`source/basic/helloworld.au3`](diffhunk://#diff-77d5e0b2473749d7e42592f3e978dd25e0e11d661b84a0ec0ebdc3d3aecd7fbfR1): Added a new "Hello World" script using AutoIt.
=> Add AutoIt language to the list of supported languages

README.md, source/basic/helloworld.au3
This pull request adds the AutoIt and VBScript languages to the list of supported languages in the project. The AutoIt language is added with a link to the AutoIt website, and the VBScript language is added with a link to the Microsoft VBScript documentation.
=> Add AutoIt and VBScript languages to the list of supported languages

README.md, source/basic/HelloWorld.carbon, source/basic/Helloworld
Carbon Language is An experimental successor to C++ (NOTE: Carbon Language is experimental)
=> Added HelloWorld.carbon

README.md, source/basic/helloworld.sas
Added a helloworld.sas file and updated the README.md
=> Added hello world in language sas

source/basic/hello_world.ring
Hello,
Hope you're doing well
As it has been requested in issue #256, I have added necessary code to print `Hello, World` in the Ring Programming Language.
If at all there is anything else needed from my end, then do let me know
Sincere apologies for my mistakes if you find any
Thanks and Regards,
Mohit Kambli
=> Fix #256: Add 'Hello world' in Ring programming language.

README.md, source/basic/HelloWorld.abap
Added a new program file in ABAP & included ABAP in README.md file
=> added hello world in ABAP

README.md
=> fix link to coffeescript file in readme

README.md, source/basic/hello_world.ex
Added Euphoria language in the documentation as well the code snippet of hello world in the source code
The issue link is: #335
=> Add Hello World in Euphoria

README.md
Added ReasonML as an available language to the README.md.
=> Added ReasonML as an available language to the README.md

README.md
This pull request adds **ActionScript** to the "Available Languages" section in the README file.  
- Adding a link to `source/basic/HelloWorld.as` for the ActionScript language.  
- Providing a reference to the [[ActionScirpt language page on Wikipedia]]
- The HelloWorld.as file was already created so I added the language in readme file.
---
---
Fixes #242
=> Added "Hello world" in ActionScript programming language.

README.md, source/basic/hello_world.v
This pull request adds  **hello world in Verilog language**  and **Verilog** to the "Available Languages" section in the README file.  
- Adding a link to `source/basic/hello_world.v` for the Verilog language.  
- Providing a reference to the [[Verilog page on Wikipedia]
---
---
Fixes #261
=> Add "Hello world" in Verilog programming language. #261

README.md
This pull request adds **Sather** to the "Available Languages" section in the README file.  
- Adding a link to `source/basic/HelloWorld.sather` for the Sather language.  
- Providing a reference to the [[Sather language page on Wikipedia]
---
---
Fixes #336
=> Added the Sather language to the readme file  #336

README.md
This pull request adds **Io** to the "Available Languages" section in the README file and the helloworld.io.
Changes include:    
- Providing a reference to the [[Io page on Wikipedia]
---
---
Fixes #250
=> Add "Hello world" in io programming language. #250

README.md
This pull request adds **LiveScript** to the "Available Languages" section in the README file.  
- Adding a link to `source/basic/HelloWorld.ls` for the LiveScript language.  
- Providing a reference to the [[LiveScript Wikipedia]
---
---
Fixes #305
=> Add LiveScript in Available languages section in readme file. #305

README.md
This pull request adds **Maple** to the "Available Languages" section in the README file.  
- Adding a link to `source/basic/HelloWorld.mpl` for the Maple language.  
- Providing a reference to the [[Maple page on Wikipedia](https://en.wikipedia.org/wiki/Maple_(software))](https://en.wikipedia.org/wiki/Maple_(software)).  
---
---
Fixes #306
=> Add Maple in Available languages section in readme file. #306

README.md
This pull request adds **Raku** to the "Available Languages" section in the README file.  
- Adding a link to `source/basic/HelloWorld.raku` for the Raku language.  
- Providing a reference to the [[Raku .org]]
---
---
Fixes #307
=> Add Raku in Available languages section in readme file. #307

README.md
This pull request adds **Scratch** to the "Available Languages" section in the README file.  
- Adding a link to `source/basic/HelloWorld.sb3` for the Scratch language.  
- Providing a reference to the [[Scratch site](https://scratch.mit.edu/)](https://scratch.mit.edu).  
---
---
Fixes #310
=> Add Scratch in Available languages section in readme file. #310

script.js, source/basic/hello_world.ring
You've forgoten to put Ring in available programming languages section in README.md.
=> Revert "Added Hello World in Ring Language "

source/basic/hello_world.babel
Added 'Hello, World!" using babel.
=> Added hello world using babel

source/basic/hello_world.fan
=> added hello world in Fantom

README.md, script.js, source/basic/hello_world.fan
I have added HelloWorld program in Fantom programming language to this project. I hope you find it useful.
=> Add Fantom programming language in readme file and show it on the website.

README.md, script.js, source/basic/hello_world.yaml
I just added Hello World in YAML language to this project. I hope it is useful for you.
=> Add Hello World program in YAML language

README.md, script.js, source/basic/hello_world.sim, source/basic/hello_world.yaml
I just added Hello World in Simula language to this project. I hope it is useful for you.
=> Add simula hello world

README.md, script.js, source/basic/hello_world.wren
**Description:**
- Brief explanation of the language:
- Wren is a lightweight scripting language designed for embedding in applications. It is fast, minimalistic, and ideal for environments where memory and performance are critical.
**Any special considerations:**
- Ensure that the Wren CLI is installed to run the code. Refer to the [Wren GitHub repository](https://github.com/wren-lang/wren) for installation instructions.
**Reference to official documentation:**
- [Wren Documentation](https://wren.io/)
=> Add Hello World example in Wren

README.md, script.js, source/basic/hello_world.b
Closes: #385 
Title: Add "Hello world" in B programming language (Predecessor to C).
=> Add Hello World in B Programming Language

README.md, script.js, source/basic/hello_world(E).e, source/basic/hello_world.dpr
Closes: #389 
Title: Add "Hello world" in Delphi programming language (Derived from Object Pascal).
=> Add delphi hello world

README.md, script.js
Closes: #390 
Title: Add "Hello world" in E programming language (Secure distributed programming).
=> Add Hello World in E Programming Language

README.md, script.js, source/basic/hello_world.zsh
Closes: #411 
Title: Add "Hello world" in Zsh programming language (Z Shell scripting language).
=> Add Hello World in Zsh programming Language

README.md, script.js, source/basic/hello_world.ksh
Closes: #392 
Title: Add "Hello world" in KornShell (ksh) programming language (Unix shell and scripting language).
=> Add ksh hello world

README.md, script.js, source/basic/hello_world.jsp, source/basic/hello_world.ksh
Closes: #391 
Title: Add "Hello world" in JSP programming language (JavaServer Pages).
=> Add jsp hello world

README.md, script.js, source/basic/hello_world.awk
Closes: #384 
Title: Add "Hello world" in Awk (Text-processing language).
=> Add awk hello world

README.md, script.js, source/basic/hello_world.do
Closes: #404 
Title: Add "Hello world" in Stata programming language (Statistical language).
=> Add stata hello world

README.md, script.js, source/basic/hello_world.dragon
Fixes #440
Added code to print "Hello, World" using Dragon programming language.
Dragon is a lightweight, multi-paradigm programming language. It emphasizes simplicity, readability, and flexibility while supporting structured, object-oriented, and functional programming paradigms.
=> Add Hello World using Dragon programming language

README.md, script.js, source/basic/helloworld.ck
=> Add Hello World example in Chunk

README.md, script.js, source/basic/helloworld.cbls
=> Add Hello World example in CobolScript

README.md, script.js, source/basic/helloworld.livecode
=> Add Hello World example in LiveCode

README.md, script.js, source/basic/helloworld.monkey
=> Add Hello World example in Monkey X

README.md, script.js, source/basic/helloworld.mq5
=> Add Hello World example in MQL

README.md, script.js, source/basic/helloworld.cl
=> Add Hello World example in OpenCL

README.md, script.js, source/basic/helloworld.pde
=> Add Hello World example in Processing

README.md, script.js, source/basic/helloworld.reb
=> Add Hello World example in Rebol

README.md, script.js, source/basic/hello_world.blaz
Closes: #386 
Title: Add "Hello world" in Blaz programming language (A high-performance language for data analytics).
Your Name: Bihan Ray
=> Add blaz hello world

README.md, script.js, source/basic/hello_world(TADS).t
Closes: #405 
Title: Add "Hello world" in TADS programming language (Text Adventure Development System).
Your Name: Bihan Ray
PS: Had to rename the file as 'hello_world(TADS).t' due to having same extension as 'TURING' Language
=> Add tads hello world

README.md, script.js, source/basic/hello_world(VB.NET).vb
Closes: #407 
Title: Add "Hello world" in VB.NET programming language (Successor to Visual Basic).
Your Name: Bihan Ray
PS: Had to rename the file as 'hello_world(VB.NET).t' due to having same extension as another file
=> Add python vb.net world

README.md, script.js, source/basic/helloworld.cow
=> Added hello world using COW

README.md, script.js, source/basic/helloworld.cow, source/basic/helloworld.oak
=> Added Hello World using OAK

index.html, script.js, styles.css
This introduces a "Back to Top" button feature to enhance user experience by allowing quick navigation to the top of the page after scrolling through the programming languages list. The button is styled with a vertical layout, displaying an upward arrow (↑) above the word "Top" for a clean and intuitive design.
- Improves navigation on a long page with many language cards.
- The vertical layout (arrow above "Top") provides a visually distinct and user-friendly design.
=> contributed to a project
